port: 8888

# Site settings
title: AkuPayu
description: 
baseurl: ""
url: "https://akupayu.pages.dev"

# Markdown settings
markdown: kramdown

# Sass settings
sass:
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# firebase
apiKey: AIzaSyBsWW-G3USjSI4NXP-6wjifcgYlRq5_O0s
authDomain: whatsgo-id.firebaseapp.com
projectId: whatsgo-id
databaseURL: https://whatsgo-id.firebaseio.com
storageBucket: whatsgo-id.appspot.com
senderId: 785900266338
appId: 1:785900266338:web:414e9b8792ec4737f4c23b
measId: G-XEGBQPYFSJ